# Generated by Django 5.1.1 on 2024-09-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='criando',
            new_name='criado',
        ),
    ]
